# Generated by Django 3.1.7 on 2021-02-25 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet', models.CharField(max_length=200)),
                ('dono', models.CharField(max_length=200)),
                ('raca', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
