# Generated by Django 3.1.7 on 2021-03-11 23:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210311_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipoPet', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='app.user')),
            ],
        ),
    ]
