# Generated by Django 3.1.7 on 2021-03-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
