# Generated by Django 3.1.7 on 2021-03-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210311_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina', models.CharField(max_length=100)),
                ('duas_doses', models.BooleanField(default=False)),
                ('tempo_segunda_dose', models.IntegerField()),
                ('tempo_renovacao', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='tipoPet',
            new_name='tipo_pet',
        ),
    ]
